const fs=require("fs");
const INPUT="data/courses.json", OUTPUT="data/courses.json", MAP="data/homepages.json";
const CONCURRENCY=6, TIMEOUT=7000, RETRIES=1, MAX_PAGES=4;
const BLOCKED=new Set(["google.com","naver.com","blog.naver.com","youtube.com","youtu.be","instagram.com","facebook.com","x.com","twitter.com","tripadvisor.com","booking.com","agoda.com","kakaomap.com","map.kakao.com","place.naver.com"]);
const host=u=>{try{return new URL(u).hostname.replace(/^www\./,"").toLowerCase()}catch{return""}};
const blocked=u=>{const h=host(u);return !h||[...BLOCKED].some(x=>h===x||h.endsWith("."+x))};
const abs=(b,h)=>{try{return new URL(h,b).href}catch{return null}};
const clean=s=>s.replace(/<script[\s\S]*?<\/script>/gi," ").replace(/<style[\s\S]*?<\/style>/gi," ").replace(/<noscript[\s\S]*?<\/noscript>/gi," ").replace(/<[^>]+>/g," ").replace(/&nbsp;/gi," ").replace(/&amp;/gi,"&").replace(/&quot;/gi,'"').replace(/&#39;/gi,"'").replace(/\s+/g," ").trim();
const title=h=>{const m=h.match(/<title[^>]*>([\s\S]*?)<\/title>/i);return m?clean(m[1]):null};
async function fetchPage(url){for(let a=0;a<=RETRIES;a++){const c=new AbortController(),t=setTimeout(()=>c.abort(),TIMEOUT);try{const r=await fetch(url,{redirect:"follow",signal:c.signal,headers:{"User-Agent":"Mozilla/5.0 (compatible; GolfCourseIndexBot/3.0)"}});if(!r.ok)throw Error(`HTTP ${r.status}`);return{url:r.url,html:await r.text()}}catch(e){if(a===RETRIES)throw e}finally{clearTimeout(t)}}}
function links(html,base){const out=[],re=/<a[^>]+href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/gi;let m;while(m=re.exec(html)){const u=abs(base,m[1]);if(u&&!blocked(u))out.push({url:u,text:clean(m[2])})}return out}
function relevant(url,html){const keys=["요금","그린피","이용요금","이용료","가격","fee","price","코스","course","예약","라운드","이용안내","캐디","카트","노캐디","셀프","워킹","야간","night","티","거리","오시는길"];const h=host(url);return links(html,url).filter(x=>host(x.url)===h).map(x=>({...x,score:keys.reduce((n,k)=>n+(`${x.text} ${x.url}`.toLowerCase().includes(k.toLowerCase())?2:0),0)})).filter(x=>x.score>0).sort((a,b)=>b.score-a.score).slice(0,MAX_PAGES)}
const money=s=>{const m=s.replace(/,/g,"").match(/\d{2,3}(?:\d{3})?/);return m?Number(m[0]):null};
function fee(t,labels){for(const l of labels){const m=t.match(new RegExp(l+"[^\\d]{0,80}(\\d{2,3}(?:,\\d{3})?)\\s*(?:원|만원)?","i"));if(m){const v=money(m[1]);if(v!=null)return v<10000?v*10000:v}}return null}
function dist(t,labels){for(const l of labels){const m=t.match(new RegExp(l+"[^\\d]{0,50}(\\d{3,4})\\s*(?:m|M|미터)?","i"));if(m)return Number(m[1])}return null}
const any=(t,a)=>a.some(x=>t.includes(x));
function fields(c,pages){const t=pages.map(x=>clean(x.html)).join("\n");let phone=null,address=null;const re=/<script[^>]+type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi;let m;while(m=re.exec(pages.map(x=>x.html).join("\n"))){try{const v=JSON.parse(m[1]);for(const j of(Array.isArray(v)?v:[v])){if(!address&&j?.address?.streetAddress)address=[j.address.addressRegion,j.address.addressLocality,j.address.streetAddress].filter(Boolean).join(" ");if(!phone&&j?.telephone)phone=j.telephone}}catch{}}phone??=(t.match(/(?:0\d{1,2})[-.\s]\d{3,4}[-.\s]\d{4}/)||[])[0]||null;address??=(t.match(/(?:서울|부산|대구|인천|광주|대전|울산|세종|경기|강원|충북|충남|전북|전남|경북|경남|제주)[^。]{5,120}(?:로|길|읍|면|동|리)[^。]{0,60}/)||[])[0]||null;
return{address,phone,weekdayFee:c.weekdayFee??fee(t,["주중 그린피","주중","평일 그린피","평일"]),weekendFee:c.weekendFee??fee(t,["주말 그린피","주말","토요일","일요일"]),caddieFee:c.caddieFee??fee(t,["캐디피","캐디 비용","캐디비"]),cartFee:c.cartFee??fee(t,["카트피","카트비","카트 비용"]),blackTee:c.blackTee??dist(t,["블랙티","Black Tee","Black"]),blueTee:c.blueTee??dist(t,["블루티","Blue Tee","Blue"]),whiteTee:c.whiteTee??dist(t,["화이트티","White Tee","White"]),redTee:c.redTee??dist(t,["레드티","Red Tee","Red"]),twoPlayer:c.twoPlayer??(any(t,["2인 플레이","2인플레이","2인 라운드"])?true:null),threePlayer:c.threePlayer??(any(t,["3인 플레이","3인플레이","3인 라운드"])?true:null),fourPlayer:c.fourPlayer??(any(t,["4인 플레이","4인플레이","4인 라운드"])?true:null),noCaddy:c.noCaddy??(any(t,["노캐디","노 캐디","무캐디"])?true:null),walking:c.walking??(any(t,["워킹","도보 라운드","셀프 라운드"])?true:null),night:c.night??(any(t,["야간 라운드","야간운영","야간 티오프","나이트"])?true:null)}}
async function pool(a,n,fn){let i=0;async function w(){while(true){const x=i++;if(x>=a.length)return;try{await fn(a[x],x)}catch(e){console.log("ERROR",a[x].name,e.message)}}}await Promise.all(Array.from({length:Math.min(n,a.length)},w))}
function map(){try{return JSON.parse(fs.readFileSync(MAP,"utf8"))}catch{return{}}}
async function main(){const d=JSON.parse(fs.readFileSync(INPUT,"utf8")),cs=d.courses||[],mp=map();console.log(`Direct homepage mode: ${cs.length} courses; search engine DISABLED`);
await pool(cs,CONCURRENCY,async(c,i)=>{const now=new Date().toISOString();const u=mp[String(c.id)]||mp[c.name]||c.homepage;if(!u){c.homepageStatus="needs_homepage";c.homepageCheckedAt=now;console.log(`[${i+1}/${cs.length}] ${c.name} -> homepage missing`);return}let p;try{p=await fetchPage(u)}catch(e){c.homepageStatus="fetch_error";c.homepageError=e.message;c.homepageCheckedAt=now;console.log(`[${i+1}/${cs.length}] ${c.name} -> ${e.message}`);return}const home={url:p.url,html:p.html};c.homepage=p.url;c.homepageTitle=title(p.html);c.homepageStatus="found";c.homepageCheckedAt=now;c.homepageSource=mp[String(c.id)]||mp[c.name]?"manual homepage map":(c.homepageSource||"existing homepage");const pages=[home];for(const x of relevant(p.url,p.html)){try{pages.push(await fetchPage(x.url))}catch{}}for(const[k,v]of Object.entries(fields(c,pages)))if((c[k]==null||c[k]==="")&&v!=null)c[k]=v;c.officialPageSources=[...new Set(pages.map(x=>x.url))].slice(0,10);c.officialInfoCheckedAt=now;c.officialInfoSource="official golf-course homepage";console.log(`[${i+1}/${cs.length}] ${c.name} -> done`)});
d.generatedAt=new Date().toISOString();d.officialInfoSummary={total:cs.length,homepageFound:cs.filter(c=>c.homepageStatus==="found").length,needsHomepage:cs.filter(c=>c.homepageStatus==="needs_homepage").length,fetchErrors:cs.filter(c=>c.homepageStatus==="fetch_error").length,searchEngineUsed:false,updatedAt:d.generatedAt};fs.writeFileSync(OUTPUT,JSON.stringify(d,null,2),"utf8");console.log(d.officialInfoSummary)}
main().catch(e=>{console.error(e);process.exit(1)});
